scrape_configs:
  - job_name: node_prometheus
    scrape_interval: 5s
    static_configs:
    - targets: ['node-exporter:9100']
    
  - job_name: windows_exporter
    scrape_interval: 5s
    static_configs:
    - targets: ['host.docker.internal:9182']
    
  - job_name: wiremock_metrics
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
    - targets: ['host.docker.internal:9090']
    
  - job_name: my_mock_simple_server
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
    - targets: ['host.docker.internal:9000']